name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dosyalari Sunucuya Kopyala
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "."
          target: "/home/ubuntu/my-portfolyo"

      - name: Docker ile Sitenin Yayina Alinmasi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/my-portfolyo
            sudo docker build -t portfolyo-site .
            sudo docker stop portfolyo-app || true
            sudo docker rm portfolyo-app || true
            sudo docker run -d -p 80:80 --name portfolyo-app portfolyo-site